name: Environment setup
description: Reusable environment setup for Python projects

inputs:
  python-version:
    description: "The version of Python to set up"
    required: true
    type: string

runs:
  using: "composite"
  steps:    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    
    - name: Install project
      run: pip install -e .
      shell: bash