name: Environment setup
description: Reusable environment setup for Python projects

inputs:
  python-version:
    description: "The version of Python to set up"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install projects
      run: pip install -e .