name: Formatting_and_linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/env_setup
        with:
          python-version: "3.13.7"

      - name: Run black (check only)
        run: black --check .